// Generated by CoffeeScript 1.6.2
var harServer, pex;

pex = pex || require('./lib/pex');

harServer = 'http://node.variable.io:1337';

pex.require([], function() {
  var IO, Platform, Window, _ref;

  _ref = pex.sys, Platform = _ref.Platform, Window = _ref.Window, IO = _ref.IO;
  return Window.create({
    settings: {
      width: 1024,
      height: 512,
      fullscreen: Platform.isBrowser
    },
    init: function() {
      if (Platform.isBrowser) {
        return this.initHTML();
      }
    },
    initHTML: function() {
      var goBtn, introDialog, makeQuery, queryInput;

      introDialog = document.getElementById('introContainer');
      queryInput = document.getElementById('query');
      goBtn = document.getElementById('goBtn');
      queryInput.addEventListener('keydown', function(e) {
        if (e.keyCode === 13) {
          return makeQuery();
        }
      });
      goBtn.addEventListener('click', function() {
        return makeQuery();
      });
      return makeQuery = function() {
        var request, url;

        url = queryInput.value;
        if (!url) {
          alert('Please enter url');
          return queryInput.focus();
        } else {
          request = harServer + '/' + encodeURIComponent(url);
          return IO.loadTextFile(request, function(response) {
            return console.log(response);
          });
        }
      };
    },
    draw: function() {}
  });
});

/*
//@ sourceMappingURL=index.map
*/
